#! /usr/local/bin/python 

"""Process emailed commands.

Called by the wrapper, stdin is the mail message, and argv[1] is the name
of the target mailing list.

Errors are redirected to logs/errors."""

import sys

sys.path.append('/home/mailman/mailman/modules')

import maillist, mm_utils

try:
    sys.stderr = mm_utils.StampedLogger("error", label = 'mailcmd',
                                        manual_reprime=1)
except IOError:
    pass                        # Oh well - SOL on redirect, errors show thru.


# Only let one program run at once per list.

if sys.argv[1] not in mm_utils.list_names():
    import mm_cfg
    mm_utils.SendTextToUser("Misconfigured list %s" % sys.argv[1],
                            ("List %s in aliases but not among "
                             "list_names?\n\n"
                             "---------- Forwarded message ----------\n"
                             "%s"
                             % (mm_cfg.MAILMAN_OWNER, sys.stdin.read())),
                            mm_cfg.MAILMAN_OWNER,
                            sender=mm_cfg.MAILMAN_OWNER)

list = maillist.MailList(sys.argv[1])

try:
    list.ParseMailCommands()
finally:
    list.Unlock()

